#!/usr/bin/env perl
package RBX::EncodeLuaProject;
use base 'Exporter';
use strict;
use warnings;

use feature 'say';

use File::Slurper qw/ read_text read_dir /;
use Data::Dumper;

use RBX::RBXMXEncoder;

our @EXPORT = qw/

/;



sub format_script {
	my ($name, $text) = @_;

	return {
			class => "Script",
			properties => {
				Disabled => [ bool => 'false' ],
				Name => [ string => $name ],
				LinkedSource => [ Content => '<null></null>' ],
				Source => [ ProtectedString => '<![CDATA[' . $text . ']]>' ],
			},
		}
}

sub format_folder {
	my ($name) = @_;
	return {
			class => "Folder",
			properties => {
				Name => [ string => $name ],
			}
		}
}


sub encode_file {
	my ($path) = @_;
	if ($path =~ /([^\/]+)\.lua\Z/) {
		return format_script($1, read_text($path));
	} else {
		die "unknown file type to encode for rbxmx: $path";
	}
}

sub encode_directory {
	my ($path) = @_;
	my @files = read_dir($path);

	my $item = format_folder($path =~ s/\A.*\/(.+)\Z/$1/r);
	$item->{children} = [ map { -f "$path/$_" ? encode_file("$path/$_") : encode_directory("$path/$_") } @files ];

	return $item
}



# say encode_rbxmx_model({
# 	class => "Folder",
# 	properties => {
# 		Name => [string => 'test_folder'],
# 	},
# 	children => [
# 		{
# 			class => "Script",
# 			properties => {
# 				Disabled => [ bool => 'false' ],
# 				Name => [string => 'test_script'],
# 				LinkedSource => [ Content => '<null></null>'],
# 				Source => [ ProtectedString => '<![CDATA[
# 		print("hello world! this was generated by RBX::RBXMXEncoder")
# 		]]>']
# 			},
# 		},
# 		{
# 			class => "Script",
# 			properties => {
# 				Disabled => [ bool => 'false' ],
# 				Name => [string => 'test_script2'],
# 				LinkedSource => [ Content => '<null></null>'],
# 				Source => [ ProtectedString => '<![CDATA[
# 		print("hello world! this was generated by RBX::RBXMXEncoder")
# 		]]>']
# 			},
# 		},
# 	],
# });


sub encode_rbxmx_lua_project {
	my ($path) = @_;

	if (-f $path) {
		return encode_rbxmx_model encode_file($path);
	} elsif (-d $path) {
		return encode_rbxmx_model encode_directory($path);
	} else {
		...
	}
}

sub main {
	my ($path) = @_;
	die "filepath required" unless defined $path;
	die "invalid path '$path'" unless -e $path;

	print encode_rbxmx_lua_project($path);
}

caller or main(@ARGV)
